"""add budget week and budget day tables

Revision ID: 4e5c2a6adaee
Revises: b8c9d0e1f2a3
Create Date: 2026-08-28 15:00:24.639803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e5c2a6adaee'
down_revision = 'b8c9d0e1f2a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget_day',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('spent', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('budget_day', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_budget_day_day'), ['day'], unique=True)

    op.create_table('budget_week',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('weekly_budget', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('budget_week', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_budget_week_week_start'), ['week_start'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget_week', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_budget_week_week_start'))

    op.drop_table('budget_week')
    with op.batch_alter_table('budget_day', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_budget_day_day'))

    op.drop_table('budget_day')
    # ### end Alembic commands ###
